# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install NodeJS
      uses: actions/setup-node@v2-beta
      
    - name: Install Yarn
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
      
    - name: Install surge
      run: sudo npm install --global surge
      
    - name: Install related libraries
      run: |
        sudo npm install --save @material-ui/core @material-ui/icons classnames csvtojson
        sudo npm install --save react-countup react-csv
    
    - name: Build React App
      run: yarn build
      
    - name: Deploy surge
      run: surge ./build asif_etapp.surge.sh --token ${{secrets.SURGE_TOKEN}}
